# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commons.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='commons.proto',
  package='org.midonet.cluster.models',
  serialized_pb=_b('\n\rcommons.proto\x12\x1aorg.midonet.cluster.models\" \n\x04UUID\x12\x0b\n\x03msb\x18\x01 \x02(\x04\x12\x0b\n\x03lsb\x18\x02 \x02(\x04\"T\n\tIPAddress\x12\x36\n\x07version\x18\x01 \x02(\x0e\x32%.org.midonet.cluster.models.IPVersion\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x02(\t\"j\n\x08IPSubnet\x12\x36\n\x07version\x18\x01 \x02(\x0e\x32%.org.midonet.cluster.models.IPVersion\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x15\n\rprefix_length\x18\x03 \x01(\r\"(\n\nInt32Range\x12\r\n\x05start\x18\x01 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x05*\x1b\n\tIPVersion\x12\x06\n\x02V4\x10\x01\x12\x06\n\x02V6\x10\x02*(\n\rRuleDirection\x12\n\n\x06\x45GRESS\x10\x00\x12\x0b\n\x07INGRESS\x10\x01*,\n\tEtherType\x12\x08\n\x03\x41RP\x10\x86\x10\x12\t\n\x04IPV4\x10\x80\x10\x12\n\n\x04IPV6\x10\xdd\x8d\x02*2\n\x08Protocol\x12\x07\n\x03TCP\x10\x06\x12\x07\n\x03UDP\x10\x11\x12\x08\n\x04ICMP\x10\x01\x12\n\n\x06ICMPV6\x10:*$\n\x08LBStatus\x12\n\n\x06\x41\x43TIVE\x10\x01\x12\x0c\n\x08INACTIVE\x10\x02\x42%\n\x1aorg.midonet.cluster.modelsB\x07\x43ommons')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_IPVERSION = _descriptor.EnumDescriptor(
  name='IPVersion',
  full_name='org.midonet.cluster.models.IPVersion',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='V4', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='V6', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=315,
  serialized_end=342,
)
_sym_db.RegisterEnumDescriptor(_IPVERSION)

IPVersion = enum_type_wrapper.EnumTypeWrapper(_IPVERSION)
_RULEDIRECTION = _descriptor.EnumDescriptor(
  name='RuleDirection',
  full_name='org.midonet.cluster.models.RuleDirection',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EGRESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INGRESS', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=344,
  serialized_end=384,
)
_sym_db.RegisterEnumDescriptor(_RULEDIRECTION)

RuleDirection = enum_type_wrapper.EnumTypeWrapper(_RULEDIRECTION)
_ETHERTYPE = _descriptor.EnumDescriptor(
  name='EtherType',
  full_name='org.midonet.cluster.models.EtherType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ARP', index=0, number=2054,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IPV4', index=1, number=2048,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IPV6', index=2, number=34525,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=386,
  serialized_end=430,
)
_sym_db.RegisterEnumDescriptor(_ETHERTYPE)

EtherType = enum_type_wrapper.EnumTypeWrapper(_ETHERTYPE)
_PROTOCOL = _descriptor.EnumDescriptor(
  name='Protocol',
  full_name='org.midonet.cluster.models.Protocol',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TCP', index=0, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UDP', index=1, number=17,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ICMP', index=2, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ICMPV6', index=3, number=58,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=432,
  serialized_end=482,
)
_sym_db.RegisterEnumDescriptor(_PROTOCOL)

Protocol = enum_type_wrapper.EnumTypeWrapper(_PROTOCOL)
_LBSTATUS = _descriptor.EnumDescriptor(
  name='LBStatus',
  full_name='org.midonet.cluster.models.LBStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACTIVE', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INACTIVE', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=484,
  serialized_end=520,
)
_sym_db.RegisterEnumDescriptor(_LBSTATUS)

LBStatus = enum_type_wrapper.EnumTypeWrapper(_LBSTATUS)
V4 = 1
V6 = 2
EGRESS = 0
INGRESS = 1
ARP = 2054
IPV4 = 2048
IPV6 = 34525
TCP = 6
UDP = 17
ICMP = 1
ICMPV6 = 58
ACTIVE = 1
INACTIVE = 2



_UUID = _descriptor.Descriptor(
  name='UUID',
  full_name='org.midonet.cluster.models.UUID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msb', full_name='org.midonet.cluster.models.UUID.msb', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lsb', full_name='org.midonet.cluster.models.UUID.lsb', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=77,
)


_IPADDRESS = _descriptor.Descriptor(
  name='IPAddress',
  full_name='org.midonet.cluster.models.IPAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='org.midonet.cluster.models.IPAddress.version', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address', full_name='org.midonet.cluster.models.IPAddress.address', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=163,
)


_IPSUBNET = _descriptor.Descriptor(
  name='IPSubnet',
  full_name='org.midonet.cluster.models.IPSubnet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='org.midonet.cluster.models.IPSubnet.version', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address', full_name='org.midonet.cluster.models.IPSubnet.address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prefix_length', full_name='org.midonet.cluster.models.IPSubnet.prefix_length', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=271,
)


_INT32RANGE = _descriptor.Descriptor(
  name='Int32Range',
  full_name='org.midonet.cluster.models.Int32Range',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='org.midonet.cluster.models.Int32Range.start', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end', full_name='org.midonet.cluster.models.Int32Range.end', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=313,
)

_IPADDRESS.fields_by_name['version'].enum_type = _IPVERSION
_IPSUBNET.fields_by_name['version'].enum_type = _IPVERSION
DESCRIPTOR.message_types_by_name['UUID'] = _UUID
DESCRIPTOR.message_types_by_name['IPAddress'] = _IPADDRESS
DESCRIPTOR.message_types_by_name['IPSubnet'] = _IPSUBNET
DESCRIPTOR.message_types_by_name['Int32Range'] = _INT32RANGE
DESCRIPTOR.enum_types_by_name['IPVersion'] = _IPVERSION
DESCRIPTOR.enum_types_by_name['RuleDirection'] = _RULEDIRECTION
DESCRIPTOR.enum_types_by_name['EtherType'] = _ETHERTYPE
DESCRIPTOR.enum_types_by_name['Protocol'] = _PROTOCOL
DESCRIPTOR.enum_types_by_name['LBStatus'] = _LBSTATUS

UUID = _reflection.GeneratedProtocolMessageType('UUID', (_message.Message,), dict(
  DESCRIPTOR = _UUID,
  __module__ = 'commons_pb2'
  # @@protoc_insertion_point(class_scope:org.midonet.cluster.models.UUID)
  ))
_sym_db.RegisterMessage(UUID)

IPAddress = _reflection.GeneratedProtocolMessageType('IPAddress', (_message.Message,), dict(
  DESCRIPTOR = _IPADDRESS,
  __module__ = 'commons_pb2'
  # @@protoc_insertion_point(class_scope:org.midonet.cluster.models.IPAddress)
  ))
_sym_db.RegisterMessage(IPAddress)

IPSubnet = _reflection.GeneratedProtocolMessageType('IPSubnet', (_message.Message,), dict(
  DESCRIPTOR = _IPSUBNET,
  __module__ = 'commons_pb2'
  # @@protoc_insertion_point(class_scope:org.midonet.cluster.models.IPSubnet)
  ))
_sym_db.RegisterMessage(IPSubnet)

Int32Range = _reflection.GeneratedProtocolMessageType('Int32Range', (_message.Message,), dict(
  DESCRIPTOR = _INT32RANGE,
  __module__ = 'commons_pb2'
  # @@protoc_insertion_point(class_scope:org.midonet.cluster.models.Int32Range)
  ))
_sym_db.RegisterMessage(Int32Range)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\032org.midonet.cluster.modelsB\007Commons'))
# @@protoc_insertion_point(module_scope)
